project:
  type: website
  output-dir: docs

website:
  title: "Introduction to R Workshop"
  navbar:
    logo: "images/DRP_Logo_only_square_transparent.png"
    left:
      - href: index.qmd
        text: Home
      - text: "Getting Started"
        href: 01-start.qmd
      - text: "Introduction"
        href: 02-IntroR.qmd
      - text: "Tidyverse"
        href: 03-tidyverse.qmd
      - text: "dplyr"
        href: 04-dplyr.qmd
      - text: "ggplot2"
        href: 05-ggplot2.qmd

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: styles.css
    toc: true
    link-external-newwindow: true

editor: visual

